"""HTML report generation."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class HTMLGenerator:
    """Generate HTML reports."""

    def __init__(self):
        """Initialize HTML generator."""
        pass

    def create_report(
        self,
        title: str,
        sections: List[Dict[str, Any]],
        output_path: Path,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Create an HTML report from structured sections.

        Args:
            title: Report title
            sections: List of section dictionaries
            output_path: Output HTML path
            **kwargs: Additional options

        Returns:
            Dictionary with file metadata
        """
        import datetime

        html = self._generate_html(title, sections)
        output_path.write_text(html, encoding="utf-8")

        return {
            "status": "success",
            "format": "html",
            "output_path": str(output_path),
            "size": output_path.stat().st_size,
            "title": title,
            "sections": len(sections),
        }

    def _generate_html(self, title: str, sections: List[Dict[str, Any]]) -> str:
        """Generate complete HTML document."""
        import datetime

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    {self._get_styles()}
</head>
<body>
    <div class="container">
        <header class="report-header">
            <h1>{title}</h1>
            <p class="generated-date">Generated: {datetime.datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
        </header>
        <main class="content">
"""

        for section in sections:
            html += self._render_section(section)

        html += """
        </main>
        <footer>
            <p>Generated by Egile Reporter</p>
        </footer>
    </div>
</body>
</html>
"""
        return html

    def _render_section(self, section: Dict[str, Any]) -> str:
        """Render a section to HTML."""
        section_type = section.get("type", "text")
        section_title = section.get("title", "")

        html = '<section class="report-section">\n'

        if section_title:
            html += f'<h2>{section_title}</h2>\n'

        if section_type == "text":
            import markdown as md

            content = section.get("content", "")
            html += f'<div class="text-content">{md.markdown(content)}</div>\n'

        elif section_type == "table":
            html += self._render_table(section)

        elif section_type == "list":
            items = section.get("items", [])
            html += "<ul>\n"
            for item in items:
                html += f"<li>{item}</li>\n"
            html += "</ul>\n"

        html += "</section>\n"
        return html

    def _render_table(self, section: Dict[str, Any]) -> str:
        """Render table to HTML."""
        data = section.get("data", [])
        if not data:
            return "<p>No data available</p>"

        columns = section.get("columns") or list(data[0].keys())

        html = '<div class="table-container"><table class="data-table">\n<thead>\n<tr>\n'
        for col in columns:
            html += f"<th>{col}</th>"
        html += "\n</tr>\n</thead>\n<tbody>\n"

        for row in data:
            html += "<tr>\n"
            for col in columns:
                value = row.get(col, "")
                if isinstance(value, float):
                    value = f"{value:,.2f}"
                html += f"<td>{value}</td>"
            html += "\n</tr>\n"

        html += "</tbody>\n</table></div>\n"
        return html

    def _get_styles(self) -> str:
        """Get CSS styles."""
        return """
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f9fafb;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        background: white;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    .report-header {
        margin-bottom: 40px;
        padding-bottom: 20px;
        border-bottom: 3px solid #2563eb;
    }

    .report-header h1 {
        font-size: 2.5rem;
        color: #1e3a8a;
        margin-bottom: 10px;
    }

    .generated-date {
        color: #6b7280;
        font-size: 0.9rem;
    }

    .content {
        margin-bottom: 40px;
    }

    .report-section {
        margin-bottom: 40px;
    }

    .report-section h2 {
        font-size: 1.8rem;
        color: #1e40af;
        margin-bottom: 15px;
        padding-bottom: 10px;
        border-bottom: 2px solid #e5e7eb;
    }

    .text-content {
        margin: 15px 0;
    }

    .text-content p {
        margin: 10px 0;
    }

    .table-container {
        overflow-x: auto;
        margin: 20px 0;
    }

    .data-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 0.95rem;
    }

    .data-table thead {
        background: #1e40af;
        color: white;
    }

    .data-table th {
        padding: 12px 15px;
        text-align: left;
        font-weight: 600;
    }

    .data-table td {
        padding: 10px 15px;
        border-bottom: 1px solid #e5e7eb;
    }

    .data-table tbody tr:nth-child(even) {
        background: #f9fafb;
    }

    .data-table tbody tr:hover {
        background: #f3f4f6;
    }

    ul, ol {
        margin: 15px 0;
        padding-left: 30px;
    }

    li {
        margin: 8px 0;
    }

    footer {
        margin-top: 60px;
        padding-top: 20px;
        border-top: 1px solid #e5e7eb;
        text-align: center;
        color: #9ca3af;
        font-size: 0.9rem;
    }

    @media print {
        body {
            background: white;
        }
        .container {
            box-shadow: none;
        }
    }
</style>
"""
